version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payments_db
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    command: >
      bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

    restart: always
    environment:
      DB_HOST: db
      DB_NAME: payments_db
      DB_USER: your_user
      DB_PASSWORD: your_password
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  db_data: